export const transportOptions = [
  { value: 'publico', label: 'Transporte publico' },
  { value: 'coche', label: 'Coche propio' },
  { value: 'moto', label: 'Moto' },
  { value: 'bicicleta', label: 'Bicicleta' },
  { value: 'a pie', label: 'A pie' },
]

export const preferenceOptions = [
  { value: 'indiferente', label: 'Indiferente' },
  { value: 'indoor', label: 'Indoor' },
  { value: 'outdoor', label: 'Outdoor' },
]

export const paceOptions = [
  { value: 'relajado', label: 'Relajado' },
  { value: 'equilibrado', label: 'Equilibrado' },
  { value: 'intenso', label: 'Intenso' },
]

export const zoneOptions = [
  {
    id: 'euskadi-general',
    label: 'Todo Euskadi',
    shortLabel: 'General',
    province: 'Pais Vasco',
    description: 'Si todavia no has decidido el area concreta, esta zona mantiene el itinerario abierto y equilibrado.',
    cities: ['Bilbao', 'Donostia', 'Vitoria-Gasteiz'],
    center: [43.1114, -2.7184],
    siteIds: ['guggenheim-bilbao', 'la-concha', 'rioja-alavesa', 'urdaibai-biosphere'],
    gridColumn: '2 / 4',
    gridRow: '2 / 4',
    accentClass: 'border-white/15 bg-white/5 text-white',
    chipClass: 'border-white/15 bg-white/10 text-white',
    glowClass: 'bg-white/10',
    summary: 'Ideal para un primer vistazo al territorio completo y para itinerarios mixtos.',
  },
  {
    id: 'bilbao-metro',
    label: 'Bilbao y entorno',
    shortLabel: 'Bilbao',
    province: 'Bizkaia',
    description: 'Nucleo urbano con cultura, gastronomia y conexiones rapidas hacia la costa.',
    cities: ['Bilbao', 'Getxo', 'Barakaldo'],
    center: [43.2630, -2.9350],
    siteIds: ['guggenheim-bilbao', 'casco-viejo-bilbao', 'museo-bellas-artes'],
    gridColumn: '1 / 3',
    gridRow: '2 / 4',
    accentClass: 'border-emerald-300/40 bg-emerald-300/10 text-emerald-50',
    chipClass: 'border-emerald-300/30 bg-emerald-300/10 text-emerald-50',
    glowClass: 'bg-emerald-300/10',
    summary: 'Muy util para escapadas urbanas, museos y gastronomia sin muchos traslados.',
  },
  {
    id: 'costa-bizkaia',
    label: 'Costa de Bizkaia',
    shortLabel: 'Costa norte',
    province: 'Bizkaia',
    description: 'Paisaje costero, rutas panoramicas y puntos iconicos como Gaztelugatxe o Urdaibai.',
    cities: ['Bermeo', 'Gernika', 'Mundaka'],
    center: [43.4330, -2.6940],
    siteIds: ['gaztelugatxe', 'urdaibai-biosphere'],
    gridColumn: '1 / 2',
    gridRow: '1 / 2',
    accentClass: 'border-cyan-300/40 bg-cyan-300/10 text-cyan-50',
    chipClass: 'border-cyan-300/30 bg-cyan-300/10 text-cyan-50',
    glowClass: 'bg-cyan-300/10',
    summary: 'Perfecta si el usuario prioriza costa, miradores y actividad al aire libre.',
  },
  {
    id: 'donostia-costa',
    label: 'Donostia y costa guipuzcoana',
    shortLabel: 'Donostia',
    province: 'Gipuzkoa',
    description: 'Ciudad, mar y cultura con una experiencia muy equilibrada entre paseo y plan urbano.',
    cities: ['Donostia', 'Getaria', 'Hernani'],
    center: [43.3183, -1.9812],
    siteIds: ['la-concha', 'peine-del-viento', 'kursaal', 'hernani-chillida-leku'],
    gridColumn: '4 / 6',
    gridRow: '1 / 4',
    accentClass: 'border-sky-300/40 bg-sky-300/10 text-sky-50',
    chipClass: 'border-sky-300/30 bg-sky-300/10 text-sky-50',
    glowClass: 'bg-sky-300/10',
    summary: 'Muy potente para turismo cultural, gastronomico y paseos junto al mar.',
  },
  {
    id: 'interior-araba',
    label: 'Interior de Araba',
    shortLabel: 'Araba',
    province: 'Araba',
    description: 'Rutas mas tranquilas, patrimonio historico y una movilidad mas comoda para coche o moto.',
    cities: ['Vitoria-Gasteiz', 'Anana', 'Laguardia'],
    center: [42.8467, -2.6716],
    siteIds: ['valle-salado', 'patrimonio-urbano'],
    gridColumn: '2 / 4',
    gridRow: '4 / 6',
    accentClass: 'border-amber-300/40 bg-amber-300/10 text-amber-50',
    chipClass: 'border-amber-300/30 bg-amber-300/10 text-amber-50',
    glowClass: 'bg-amber-300/10',
    summary: 'Buena base para planes relajados, patrimonio y recorridos en coche.',
  },
  {
    id: 'rioja-alavesa',
    label: 'Rioja Alavesa',
    shortLabel: 'Rioja',
    province: 'Araba',
    description: 'Enoturismo, paisajes y pueblos historicos con un perfil muy concreto y diferenciador.',
    cities: ['Laguardia', 'Labastida', 'Samaniego'],
    center: [42.5487, -2.5856],
    siteIds: ['rioja-alavesa'],
    gridColumn: '4 / 6',
    gridRow: '4 / 6',
    accentClass: 'border-violet-300/40 bg-violet-300/10 text-violet-50',
    chipClass: 'border-violet-300/30 bg-violet-300/10 text-violet-50',
    glowClass: 'bg-violet-300/10',
    summary: 'Muy buena para gastronomia, vino y una experiencia premium de interior.',
  },
]

export const siteOptions = [
  {
    id: 'guggenheim-bilbao',
    label: 'Museo Guggenheim Bilbao',
    city: 'Bilbao',
    province: 'Bizkaia',
    setting: 'indoor',
    tags: ['arte', 'arquitectura', 'icono'],
    transport: ['publico', 'coche', 'moto', 'bicicleta'],
    coordinates: [43.2686, -2.9379],
    durationHours: 2.5,
    priority: 98,
    description: 'Visita imprescindible para un plan cultural contemporaneo en el corazon de Bilbao.',
  },
  {
    id: 'casco-viejo-bilbao',
    label: 'Casco Viejo de Bilbao',
    city: 'Bilbao',
    province: 'Bizkaia',
    setting: 'outdoor',
    tags: ['gastronomia', 'paseo', 'historia'],
    transport: ['publico', 'coche', 'moto', 'a pie'],
    coordinates: [43.2575, -2.9248],
    durationHours: 3,
    priority: 92,
    description: 'Recorrido urbano con gastronomia, comercio local y calles historicas.',
  },
  {
    id: 'gaztelugatxe',
    label: 'San Juan de Gaztelugatxe',
    city: 'Bermeo',
    province: 'Bizkaia',
    setting: 'outdoor',
    tags: ['costa', 'naturaleza', 'mirador'],
    transport: ['coche', 'moto'],
    coordinates: [43.4410, -2.7840],
    durationHours: 4,
    priority: 96,
    description: 'Plan de costa con vistas potentes y actividad al aire libre.',
  },
  {
    id: 'la-concha',
    label: 'Playa de La Concha',
    city: 'Donostia',
    province: 'Gipuzkoa',
    setting: 'outdoor',
    tags: ['playa', 'paseo', 'relax'],
    transport: ['publico', 'coche', 'moto', 'bicicleta'],
    coordinates: [43.3181, -1.9891],
    durationHours: 2,
    priority: 95,
    description: 'Paseo costero ligero para una jornada relajada en San Sebastian.',
  },
  {
    id: 'peine-del-viento',
    label: 'Peine del Viento',
    city: 'Donostia',
    province: 'Gipuzkoa',
    setting: 'outdoor',
    tags: ['arte', 'costa', 'fotografia'],
    transport: ['publico', 'coche', 'moto', 'bicicleta'],
    coordinates: [43.3140, -2.0086],
    durationHours: 1.5,
    priority: 88,
    description: 'Mirador artistico junto al mar, ideal para una parada corta.',
  },
  {
    id: 'kursaal',
    label: 'Kursaal y paseo de Zurriola',
    city: 'Donostia',
    province: 'Gipuzkoa',
    setting: 'indoor',
    tags: ['eventos', 'arquitectura', 'cultura'],
    transport: ['publico', 'coche', 'moto', 'bicicleta'],
    coordinates: [43.3226, -1.9807],
    durationHours: 2,
    priority: 84,
    description: 'Bloque cultural urbano con espacio para eventos y paseo moderno.',
  },
  {
    id: 'rioja-alavesa',
    label: 'Rioja Alavesa',
    city: 'Laguardia',
    province: 'Araba',
    setting: 'outdoor',
    tags: ['vino', 'paisaje', 'gastronomia'],
    transport: ['coche', 'moto'],
    coordinates: [42.5453, -2.5891],
    durationHours: 5,
    priority: 90,
    description: 'Ruta enoturistica con pueblos historicos y experiencia gastronomica.',
  },
  {
    id: 'valle-salado',
    label: 'Valle Salado de Añana',
    city: 'Añana',
    province: 'Araba',
    setting: 'outdoor',
    tags: ['patrimonio', 'naturaleza', 'historia'],
    transport: ['coche', 'moto'],
    coordinates: [42.7792, -2.9847],
    durationHours: 2.5,
    priority: 86,
    description: 'Paisaje historico y didactico con recorrido al aire libre.',
  },
  {
    id: 'museo-bellas-artes',
    label: 'Museo de Bellas Artes de Bilbao',
    city: 'Bilbao',
    province: 'Bizkaia',
    setting: 'indoor',
    tags: ['arte', 'museo', 'lluvia'],
    transport: ['publico', 'coche', 'moto'],
    coordinates: [43.2664, -2.9407],
    durationHours: 2,
    priority: 87,
    description: 'Bloque cultural solido para un plan indoor bien resuelto.',
  },
  {
    id: 'hernani-chillida-leku',
    label: 'Chillida Leku',
    city: 'Hernani',
    province: 'Gipuzkoa',
    setting: 'indoor',
    tags: ['arte', 'escultura', 'jardin'],
    transport: ['coche', 'moto', 'publico'],
    coordinates: [43.2689, -1.9574],
    durationHours: 2.5,
    priority: 89,
    description: 'Coleccion artistica y entorno verde para una experiencia equilibrada.',
  },
  {
    id: 'urdaibai-biosphere',
    label: 'Reserva de Urdaibai',
    city: 'Gernika',
    province: 'Bizkaia',
    setting: 'outdoor',
    tags: ['naturaleza', 'observacion', 'senderismo'],
    transport: ['coche', 'moto', 'bicicleta'],
    coordinates: [43.3830, -2.6840],
    durationHours: 4,
    priority: 94,
    description: 'Plan natural con rutas y miradores para el Pais Vasco mas verde.',
  },
]

export const eventOptions = [
  {
    id: 'festival-jazz-bilbao',
    label: 'Bilbao Jazz Festival',
    city: 'Bilbao',
    province: 'Bizkaia',
    setting: 'indoor',
    tags: ['musica', 'evento', 'noche'],
    transport: ['publico', 'coche'],
    coordinates: [43.2630, -2.9350],
    durationHours: 3,
    priority: 91,
    description: 'Evento cultural en sala con facil combinacion urbana.',
  },
  {
    id: 'feria-del-pescado',
    label: 'Feria gastronomica costera',
    city: 'Getaria',
    province: 'Gipuzkoa',
    setting: 'outdoor',
    tags: ['gastronomia', 'mercado', 'costa'],
    transport: ['coche', 'moto'],
    coordinates: [43.3330, -2.1660],
    durationHours: 2.5,
    priority: 85,
    description: 'Mercado y degustacion con fuerte componente local.',
  },
  {
    id: 'patrimonio-urbano',
    label: 'Ruta de patrimonio urbano',
    city: 'Vitoria-Gasteiz',
    province: 'Araba',
    setting: 'outdoor',
    tags: ['historia', 'caminar', 'patrimonio'],
    transport: ['publico', 'coche', 'bicicleta'],
    coordinates: [42.8467, -2.6716],
    durationHours: 3,
    priority: 88,
    description: 'Recorrido abierto para completar un itinerario cultural y ligero.',
  },
]

export function getSiteById(siteId) {
  return siteOptions.find((site) => site.id === siteId) ?? null
}

export function getZoneById(zoneId) {
  return zoneOptions.find((zone) => zone.id === zoneId) ?? null
}

export function getSitesByIds(siteIds = []) {
  const normalizedIds = new Set(siteIds.filter(Boolean))

  return siteOptions.filter((site) => normalizedIds.has(site.id))
}

export function getCatalogSeed() {
  return {
    places: siteOptions,
    events: eventOptions,
    zones: zoneOptions,
    transportOptions,
    preferenceOptions,
    paceOptions,
  }
}